### ISSUE TITLE
OperationalError: (sqlite3.OperationalError) no such column: backend

### ISSUE THREAD

**Issue by hzy1992** [airbnb/superset#2932] opened 2017-06-09 03:53 UTC
### Superset version
0.17.6

when I in datasource list page, click the column header then return the error:

### error

> sqlalchemy.exc.OperationalError
> OperationalError: (sqlite3.OperationalError) no such column: backend [SQL: u'SELECT dbs.created_on AS dbs_created_on, dbs.changed_on AS dbs_changed_on, dbs.id AS dbs_id, dbs.verbose_name AS dbs_verbose_name, dbs.database_name AS dbs_database_name, dbs.sqlalchemy_uri AS dbs_sqlalchemy_uri, dbs.password AS dbs_password, dbs.cache_timeout AS dbs_cache_timeout, dbs.select_as_create_table_as AS dbs_select_as_create_table_as, dbs.expose_in_sqllab AS dbs_expose_in_sqllab, dbs.allow_run_sync AS dbs_allow_run_sync, dbs.allow_run_async AS dbs_allow_run_async, dbs.allow_ctas AS dbs_allow_ctas, dbs.allow_dml AS dbs_allow_dml, dbs.force_ctas_schema AS dbs_force_ctas_schema, dbs.extra AS dbs_extra, dbs.perm AS dbs_perm, dbs.changed_by_fk AS dbs_changed_by_fk, dbs.created_by_fk AS dbs_created_by_fk \nFROM dbs ORDER BY backend asc\n LIMIT ? OFFSET ?'] [parameters: (500, 0)]
> 
> Traceback (most recent call last)
> File "/Library/Python/2.7/site-packages/flask/app.py", line 1997, in __call__
> return self.wsgi_app(environ, start_response)
> File "/Library/Python/2.7/site-packages/flask/app.py", line 1985, in wsgi_app
> response = self.handle_exception(e)
> File "/Library/Python/2.7/site-packages/flask/app.py", line 1540, in handle_exception
> reraise(exc_type, exc_value, tb)
> File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
> response = self.full_dispatch_request()
> File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
> rv = self.dispatch_request()
> File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "/Library/Python/2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
> return f(self, *args, **kwargs)
> File "/Library/Python/2.7/site-packages/flask_appbuilder/views.py", line 450, in list
> widgets = self._list()
> File "/Library/Python/2.7/site-packages/flask_appbuilder/baseviews.py", line 870, in _list
> page_size=page_size)
> File "/Library/Python/2.7/site-packages/flask_appbuilder/baseviews.py", line 786, in _get_list_widget
> count, lst = self.datamodel.query(joined_filters, order_column, order_direction, page=page, page_size=page_size)
> File "/Library/Python/2.7/site-packages/flask_appbuilder/models/sqla/interface.py", line 112, in query
> return count, query.all()
> File "/Library/Python/2.7/site-packages/sqlalchemy/orm/query.py", line 2703, in all
> return list(self)
> File "/Library/Python/2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
> return self._execute_and_instances(context)
> File "/Library/Python/2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
> result = conn.execute(querycontext.statement, self._params)
> File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
> return meth(self, multiparams, params)
> File "/Library/Python/2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
> return connection._execute_clauseelement(self, multiparams, params)
> File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
> compiled_sql, distilled_params
> File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
> context)
> File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
> exc_info
> File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
> reraise(type(exception), exception, tb=exc_tb, cause=cause)
> File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
> context)
> File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
> cursor.execute(statement, parameters)

**Comment by xrmx** [comment] 2017-06-09 07:41
Have you run the migrations?

**Comment by hzy1992** [comment] 2017-06-09 08:15
sorry, What's the 'migrations' mean?

**Comment by xrmx** [comment] 2017-06-09 08:17
Means it looks like your database is out of sync with your code, have you updated superset version?
http://airbnb.io/superset/installation.html#upgrading

**Comment by hzy1992** [comment] 2017-06-09 08:29
Yes, i have done it.
I build the project myself and run the upgrade command
the result is same

**Comment by RichRadics** [comment] 2017-06-16 15:03
This is a duplicate of #1018.

**Comment by xrmx** [comment] 2017-06-16 15:08
Indeed, closing then.

**Closed by xrmx** 2017-06-16 15:08 UTC
