### ISSUE TITLE
module 'superset.views.core' has no attribute 'TableColumnInlineView'

### ISSUE THREAD

**Issue by shaweiguo** [airbnb/superset#2437] opened 2017-03-19 11:18 UTC
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Superset 0.17.1

### Expected results
When i check table column Groupable (or Filterable etc. ), but failed with AttributeError: module 'superset.views.core' has no attribute 'TableColumnInlineView'.

### Actual results
_Traceback (most recent call last):
  File ".virtualenvs/py360/lib/python3.6/site-packages/superset/views/core.py", line 107, in wraps
    return f(self, *args, **kwargs)
  File ".virtualenvs/py360/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 52, in wraps
    return f(self, *args, **kwargs)
  File ".virtualenvs/py360/lib/python3.6/site-packages/superset/views/core.py", line 1237, in checkbox
    model_view_cls = getattr(views, model_view)
AttributeError: module 'superset.views.core' has no attribute 'TableColumnInlineView'_

### Steps to reproduce
open Sources -> Tables -> edit a table -> List Table Column -> check Groupable or Filterable etc.

**Comment by shaweiguo** [comment] 2017-03-20 02:26
v0.15.4 is ok.

**Comment by xrmx** [comment] 2017-03-24 18:49
Yeah this looks like a regression from the connector rework. @mistercrunch i've tried to get the view from the flask blueprint registry but *surprise* i get only blueprints from there and not the actual view class. Should we add a list of related view to the datasource model or we should add a new item in the config like we do for datasources?

**Comment by xrmx** [comment] 2017-03-26 10:59
Should be fixed in 
https://github.com/airbnb/superset/commit/59d5fcf88c0f484a189c7f02968982b2d39512ad

**Closed by xrmx** 2017-03-26 10:59 UTC
Labels: bug
