### ISSUE TITLE
[explorev2] dashboard slice links all send to the same slice

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/superset#1860] opened 2016-12-16 22:21 UTC

**Comment by ascott** [comment] 2016-12-16 23:32
digging into this a little bit. looks like on first slice click from a dashboard, it loads the correct slice, and for every other slice click after that it loads the same slice as the first one. still digging into the cause.

**Comment by ascott** [comment] 2017-01-05 20:14
@vera-liu fixed with https://github.com/airbnb/superset/pull/1894

**Closed by ascott** 2017-01-05 20:14 UTC
Labels: explore-v2
