### ISSUE TITLE
export csv is not giving latest data

### ISSUE THREAD

**Issue by malleshm** [airbnb/superset#1635] opened 2016-11-18 06:29 UTC
I have opened slice and changed some group by and ran "query" after that try to export in csv format but not getting latests data.

Any update on this.

**Comment by vera-liu** [comment] 2016-11-30 17:57
Couldn't reproduce this bug, is this on latest master? We had problem with csv before and was solved in [https://github.com/airbnb/superset/pull/1292](url)

**Comment by malleshm** [comment] 2016-12-05 12:58
no this one was on old master set(caravel).

Open any saved slice 
http://localhost:8088/caravel/explore/table/1/?flt_col_0=source&datasource_id=3&flt_op_0=in&slice_id=37&viz_type=sankey&row_limit=5000&metric=sum__value&having=&groupby=source&groupby=target&json=false&collapsed_fieldsets=&datasource_name=energy_usage&slice_name=Energy+Sankey&where=&datasource_type=table&flt_eq_0=

Then change GroupBy(source or target), run the query.
After this if u ll try do CSV export we will not get latest groupby column result, we will get same saved slice details.

**Comment by vera-liu** [comment] 2016-12-05 18:02
Seems to be working in latest master, I believe this was fixed in [https://github.com/airbnb/superset/pull/1292](url)

**Closed** 2017-01-05 20:27 UTC
Labels: explore-v2
