### ISSUE TITLE
Axis labels no longer displaying properly

### ISSUE THREAD

**Issue by jfeng15** [airbnb/superset#2279] opened 2017-02-27 01:29 UTC
Axis labels are no longer displaying properly with the latest push to production.  Please visit https://superset.d.musta.ch/superset/dashboard/meta/ to reproduce the issue.

<img width="888" alt="screen shot 2017-02-26 at 5 25 43 pm" src="https://cloud.githubusercontent.com/assets/8325152/23345845/013907fe-fc49-11e6-8141-01137fee3030.png">

**Comment by ascott** [comment] 2017-02-27 18:53
duplicate of https://github.com/airbnb/superset/issues/2264

**Closed by ascott** 2017-02-27 18:53 UTC
