### ISSUE TITLE
[explore] druid slice errors

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#2271] opened 2017-02-25 03:48 UTC
https://airbnb.quip.com/sacgAluVmKAQ

**Comment by nishantmonu51** [comment] 2017-02-25 11:05
@ascott can you add some more description or SNAPSHOTS for the issue. 
The link points to airbnb dashboard which everyone might not have access to.

**Comment by vera-liu** [comment] 2017-02-27 17:58
this was caused by filters missing operator 'not in', solved by adding back filter operators

**Comment by vera-liu** [comment] 2017-02-27 19:14
Fixed with https://github.com/airbnb/superset/pull/2288

**Closed by vera-liu** 2017-02-27 19:14 UTC
Labels: druid
