### ISSUE TITLE
no module named pwd

### ISSUE THREAD

**Issue by wangbincumt** [airbnb/superset#3010] opened 2017-06-20 23:40 UTC
I use window 7, in last step ：superset runserver。it has error：no module named pwd
i install pycrypto，it doesn't work

**Comment by Subhash9325** [comment] 2017-06-21 03:03
The error is caused by http://github.com/google/oauth2client/issues/578.

It will be fixed with a new AppEngine SDK. Else you can downgrade the version of the oauth2client library in your app.yaml file.

**Closed** 2017-06-21 04:47 UTC
Labels: help wanted, windows

**Comment by wangdongjie100** [comment] 2017-10-18 11:50
Have you solved this problem?
