### ISSUE TITLE
How to export csv data in dashboard page

### ISSUE THREAD

**Issue by data-strategy** [airbnb/superset#2433] opened 2017-03-17 15:26 UTC
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15

### Expected results
Export data from dashboard page

### Actual results
Need to click explore button, go to slice, then can export data.
Is it possible to export data from dashboard page, then unnecessary to click again to slice page. 
How to do this?

**Comment by mistercrunch** [comment] 2017-03-17 16:05
I guess the widget header in the dashboard could evolve to expose more options, perhaps the ones that are not very commonly used could be buried in a popover

**Comment by pajachiet** [comment] 2017-05-18 17:38
Seems to be a duplicate of https://github.com/airbnb/superset/issues/1304

**Comment by xrmx** [comment] 2017-05-18 19:33
@pajachiet Indeed! Thanks!

**Closed by xrmx** 2017-05-18 19:33 UTC
